radicle-dev/radicle-client-services

- Cargo.lock
- Cargo.toml
- README.md
- org-node/Cargo.toml
- org-node/README.md
- org-node/src/client.rs
- org-node/src/client/handle.rs
- org-node/src/client/signer.rs
- org-node/src/lib.rs
- org-node/src/main.rs
> [org-node] Initial event-subscriber implementation

- Cargo.lock
- Cargo.toml
- http-api/Cargo.toml
- http-api/Dockerfile
- http-api/src/main.rs
- org-node/Cargo.toml
- org-node/Dockerfile
- org-node/src/main.rs
- shared/Cargo.toml
- shared/src/lib.rs
- shared/src/logging.rs
As a bonus: `RUST_LOG`'s value was being ignored.  It no longer is.
> Make logging work with GCP

- docker-compose.yml
> Add a container for git-server

- Caddyfile
- docker-compose.yml
> Integrate reverse proxy into docker-compose cluster

- git-server/Dockerfile
> Install git in the git-server container

- docker-compose.yml
> Reduce hyper logging in git-server

- org-node/src/lib.rs
This ensures that if any task fails, we fail the entire process so that
it can be restarted.
> org-node: Exit when a task fails

- Caddyfile
Fixes an issue reported by @rudolfs
> Set proper port for revser-proxying git-server

- org-node/src/client.rs
- org-node/src/lib.rs
- org-node/src/main.rs
> [org-node] add Client::track_peers process for tracking and fetching remote peers

- http-api/src/lib.rs
Signed-off-by: Ryan <ryan.michael.tate@gmail.com>
> http-api: fix warp v1 projects path

- http-api/src/lib.rs
By default, when listing project's info (in route `/v1/projects/:urn`), it looks for [remote branch](https://github.com/radicle-dev/radicle-client-services/blob/b795d6834437326d6593d828d3e92656e75d4a13/http-api/src/lib.rs#L333-L336), which is only created on replication. We can fallback to local branch, in case it's missing.
> http-api: fallback to local branch when remote missing in project_info

- Cargo.lock
- git-server/Cargo.toml
- git-server/src/error.rs
- git-server/src/lib.rs
Closes https://github.com/radicle-dev/radicle-client-services/issues/72
> git-server: add support for project alias

- http-api/src/lib.rs
Two changes here:
1. Moved `root_handler` to root, that's what users should see when they hit `/`.
2. Added `/v1/projects` handler, which lists all projects e.g:
```json
[{"name":"delete-this","urn":"rad:git:hnrkyfoxs5xp45wg1p8q3dkh74qyebqaeunqo"}]
```
> http-api: Add projects route to api

- http-api/src/lib.rs
This PR adds a new route under `projects/<project>/commits/<head>` and returns a listing of all commit starting from <head>.
The output is the following:
```json
{
"headers": [
{
"sha1": "3a1625e7754a6f53fc5f63973ede972da5e15c25",
"author": {
"name": "Alexis Sellier",
"email": "self@cloudhead.io"
},
"summary": "Use org profile for anchor",
"description": "",
"committer": {
"name": "Alexis Sellier",
"email": "self@cloudhead.io"
},
"committerTime": 1629395407
},
// Much more...
],
"stats": {
"commits": 386,
"branches": 0,
"contributors": 3
}
} 
```
> Add commit listing

- http-api/src/lib.rs
This PR adds a `peer_id` to the routes to obtain the information according to a specific peer id.
Since it's a breaking change, we should implement a migration strategy.
> Add specific peer id to route params

- git-server/bin/pre_receive.rs
- git-server/src/hooks/pre_receive.rs
- git-server/src/hooks/types.rs
> git-server: Check cert status in pre-receive

- git-server/src/hooks/post_receive.rs
> git-server: Fix and simplify HEAD setting

- Cargo.lock
- Cargo.toml
- git-server/src/error.rs
- git-server/src/hooks/mod.rs
- git-server/src/hooks/post_receive.rs
- git-server/src/hooks/storage.rs
- http-api/src/error.rs
- http-api/src/lib.rs
- org-node/src/client.rs
> Update radicle-link and add tracking

- git-server/Dockerfile
- git-server/docker/start-up.sh
> Initialize working directory with radicle-service-init

- http-api/src/lib.rs
This PR adds a route to see the header and changeset of a specific commit.
The route is `/projects/:project/commit/:sha``
> Add commit view route

- http-api/src/lib.rs
- http-api/src/project.rs
There is surely a way to make this more compact, or efficient, but pretty happy to have made it work 😃
> http-api: Add project alias fetching

- http-api/src/lib.rs
This PR adds the possibility to fetch the commit history for a date range.
It allows to add the `since` and `until` query param in a UNIX Timestamp format, e.g.
`/projects/<urn>/commits?since=1643629969&until=1643829969`
> http-api: Add date range to commit history route

- git-server/Dockerfile
- git-server/docker/radicle-git-server.sh
- git-server/src/hooks/mod.rs
- http-api/src/lib.rs
> git-server: Make it possible to override some args

- Cargo.lock
- Cargo.toml
- http-api/Cargo.toml
> http-api: Update radicle-surf and blob support

- http-api/src/lib.rs
> http-api: Improve project root handler

- .env.maple
- .env.pine
- .env.seed
- .env.willow
- .github/workflows/deployables.yml
- docker-compose.yml
[...] and add the ability to deploy old revisions too (not just always the latest one).
> Most robust deployment code

- http-api/Dockerfile
- http-api/src/error.rs
- http-api/src/lib.rs
> http-api: Fix a few things relating to verified commits

- http-api/src/commit.rs
- http-api/src/lib.rs
- http-api/src/project.rs
> http-api: Fingerprint improvements

- Cargo.lock
- Cargo.toml
- git-server/src/hooks/post_receive.rs
- git-server/src/hooks/types.rs
- git-server/src/lib.rs
- git-server/src/main.rs
- http-api/src/lib.rs
- scripts/reset.sh
- shared/Cargo.toml
- shared/src/lib.rs
> git-server: Add support for profiles

- http-api/src/error.rs
- http-api/src/issues.rs
- http-api/src/lib.rs
Signed-off-by: Sebastian Martinez <me@sebastinez.dev>
> http-api: Resolve issue and comment authors

- http-api/src/v1/projects.rs
This PR adds an endpoint at `/v1/projects/:project/activity` that returns the committer timestamps of all commits done in the past year, starting at the project HEAD.
Since we are not mapping `Commit` to `Header` or doing other filtering and sorting, this should be a fast way to obtain the repo activity.
The grouping by week, I left to be done by `radicle-interface` since we would eventually be interested in grouping or sorting these timestamps differently.
> http-api: Add project activity endpoint
