- http-api/Dockerfile
- org-node/Cargo.toml
- org-node/Dockerfile
Cause: cargo install was selecting a different dependency plan than
outside of a container due to 'cargo install' ignoring Cargo.lock
by default.
> Fix an websocket bad request issue

- docker-compose.yml
It requires the `DOMAIN` environment variable be set up for the TLS to work without a warning on the web browser side of things.  E.g. `export DOMAIN=example.com`.
> Add Caddy reverse proxy for automatic TLS

- Cargo.lock
- git-server/Cargo.toml
- git-server/Dockerfile
- git-server/README.md
- git-server/bin/post_receive.rs
- git-server/bin/pre_receive.rs
- git-server/src/error.rs
- git-server/src/hooks/mod.rs
- git-server/src/hooks/post_receive.rs
- git-server/src/hooks/pre_receive.rs
- git-server/src/hooks/types.rs
- git-server/src/lib.rs
- git-server/src/main.rs
- org-node/src/client.rs
- org-node/src/client/handle.rs
- org-node/src/lib.rs
Authenticates git push requests using signed push certificates, e.g. `git push --sign`, verified in the newly created `pre-receive` hook  binary.
Additionally sends a request over unix sockets to `org-node` to update the signed refs, handled in the newly created `post-receive` hook binary.
> [git-server] hooks for `receive-pack` (git push) events

- org-node/src/client/signer.rs
- org-node/src/identity.rs
- org-node/src/lib.rs
- org-node/src/main.rs
This change allows an identity file to be specified that is encrypted
and stored using the FileStorage found in radicle-keystore.
It adds an optional parameter `--identity-passphrase` which expects the
passphrase that decrypts the file to get the signing key.
Signed-off-by: Fintan Halpenny <fintan.halpenny@gmail.com>
> org-node: unlock encrypted key

- git-server/src/hooks/pre_receive.rs
- git-server/src/hooks/types.rs
fixes the case where --allow-unauthorized flag is
not set, and therefore neither is the ENV
RADICLE_ALLOW_UNAUTHORIZED_KEYS.
Adds Option<bool> and checks .is_some() in the
pre-receive hook.
Signed-off-by: Ryan <ryan.michael.tate@gmail.com>
> git-server: fix for optional allow unauth keys

- http-api/Cargo.toml
I propose to increment the version of the http-api to 0.2.0 due to the implementation of the project listing.
It would be helpful to check in the radicle-interface before querying the project list.
> Increment http-api version to 0.2.0

- Cargo.lock
- Cargo.toml
- git-server/Cargo.toml
- http-api/src/lib.rs
- org-node/Cargo.toml
- org-node/src/client.rs
- org-node/src/lib.rs
- rust-toolchain
Since radicle-link now runs on stable rust, we also move to stable.
> Update radicle-link, move to 'stable'

- .github/workflows/e2e-tests.yml
Triggers this GitHub Actions job: https://github.com/cloudhead/radicle-client-services-e2e-tests/runs/4471306560?check_suite_focus=true
> Trigger end-to-end tests on a pull request

- http-api/src/error.rs
- http-api/src/lib.rs
- http-api/src/project.rs
This PR adds 2 new routes `/projects/<urn>/remotes` and `/projects/<urn>/remotes/<peerid>` which shows a list of remotes with replicated identities.
And reverts the peer id argument addition from the source code routes and project info.
It also refactors some querying into helper functions to reduce code duplication.
> Add remotes routes

- git-server/Dockerfile
- http-api/Dockerfile
- org-node/Dockerfile
`org-node` docker image can't currently be run as buster debian has GLIBC 2.28-10, whereas 2.29 is needed by stable rust:
```
/lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found
```
> Dockerfile: Bump all to bullseye and copy post-receive for git-server

- http-api/src/error.rs
- http-api/src/lib.rs
This PR uses the local state of a project for checking the default branch head commit, and instead of going else for a remote branch it returns a 404 error
> http-api: Utilize local state for project info

- http-api/src/lib.rs
This PR adds `default_branch` and `maintainers` to the `project_root_handler`.
This allows us in the interface to skip the info query for good while rendering project widgets, and use only the information provided by the project listing.
> Add default_branch and indirect remotes

- .github/workflows/deployables.yml
This should fix `GIT_HEAD` issue, please merge and re-deploy.
> ci: checkout code and pass context to get `.git`

- http-api/src/error.rs
- http-api/src/lib.rs
- http-api/src/project.rs
To make the `radicle-http-api` compatible with `upstream-seed` we fall back to calculating the current head from the project delegates instead of relying on it being set by the seed peer.
> http-api: derive local head from delegates if none set

- http-api/src/lib.rs
- http-api/src/main.rs
This makes `radicle-http-api` aware of librad profiles by setting the RAD_HOME environment variable. The `--root` option behaves as before.
> http-api: add support for RAD_HOME env var

- Cargo.lock
- Cargo.toml
- http-api/Cargo.toml
- http-api/src/error.rs
- http-api/src/lib.rs
- http-api/src/project.rs
- org-node/Cargo.toml
- org-node/src/client.rs
This patch removes the use of the radicle-daemon package. The only use
of it was to import code from the re-exported librad package. Instead
we just use the librad dependency and import straight from there.
Signed-off-by: Fintan Halpenny <fintan.halpenny@gmail.com>
> deps: remove radicle-daemon

- http-api/src/lib.rs
This PR is needed for a correct working of the code activity graphs in `radicle-interface`
- We limit the amount of commits to 30 when no date range is being passed i.e. `since` + `until`
- If a date range is passed we return all the commits inside that date range, on a single "page"
> http-api: Improve pagination behaviour

- .gitignore
- Cargo.lock
- http-api/Cargo.toml
- http-api/src/auth.rs
- http-api/src/error.rs
- http-api/src/lib.rs
This PR adds new `sessions` route `handlers` and `filters` to allow users to sign into the `http-api`.
**Process:**
- We create a `Unauthorized` session for every POST request we receive on `/v1/sessions` that lasts for 60 seconds.
- Once we receive a PUT request with the SIWE raw message and the signature done by the user and verify the authenticity, origin and timestamps, we upgrade the session to a `Authorized` session and keep the session alive for 1 week
- We periodically check the active `Unauthorized` & `Authorized` sessions for expiration and remove them if necessary.
**Implementation:**
The idea is to provide the session id in the `Authorization` header, for the routes which we want to protect.
> http-api: Add sessions with SIWE authentication

- http-api/src/lib.rs
This PR makes use of the string passed to the `SiweVerificationError` and `SiweParserError`.
> http-api: Improve Siwe error output

- Cargo.lock
- Cargo.toml
- http-api/Cargo.toml
- http-api/src/lib.rs
- http-api/src/patches.rs
This PR closes #155 
- Converts patch endpoints from using tags to COBs.
- Adds an endpoint for single patch retrieval
- Adds partial and complete diffs
> Various patches endpoint updates

- http-api/src/lib.rs
- http-api/src/v1/projects.rs
warp automatically would log the binding address on startup, e.g.:
```
Jul 25 14:42:23.464  INFO Server::run{addr=0.0.0.0:8778}: warp::server: listening on http://0.0.0.0:8777
```
axum doesn't so we add a manual log in https://github.com/radicle-dev/radicle-client-services/commit/d1e24ea22aefdcde55ac1c26ea760663903041ea
--------
in `/projects/:project/tree/:prefix/*path` route, renaming `:prefix` to `:sha` would make sense making it easier to understand.
> a few minor fixes to api

- http-api/src/v1/projects.rs
In the `history_handler` we are currently re assigning the amount of commits after filtering them
```rs
commits.stats.commits = headers.len();
```
We should remove that, so we can make use of the total commit count on the web ui
> http-api: Remove commit count reassignment

- Cargo.lock
- http-api/Cargo.toml
- http-api/src/error.rs
- http-api/src/lib.rs
- http-api/src/v1/projects.rs
From 30 seconds down to ~7 on my machine (`Aug 29 13:03:41.805  INFO request{method=GET uri=/v1/projects status=200 latency=6.635511333s}: radicle_http_api: Processed`).  99% of time is spent blocked on storage pool `get()`, so that's the bottleneck preventing further optimisation.
> Improve project listing speed

- Cargo.lock
- git-server/Cargo.toml
- git-server/src/main.rs
- http-api/Cargo.toml
- http-api/src/main.rs
- shared/Cargo.toml
- shared/src/lib.rs
- shared/src/logging.rs
Sample:
```
ts=2022-08-30T09:21:24.261319Z level=info target=radicle_http_api message="version 0.2.0-c9f1d72"
ts=2022-08-30T09:21:24.262506Z level=info target=shared message="Profile REDACTED loaded..."
ts=2022-08-30T09:21:24.271943Z level=info target=radicle_http_api message="listening on http://0.0.0.0:8777"
ts=2022-08-30T09:21:36.622438Z level=info target=radicle_http_api message=Processed method=GET uri=/v1/projects status=200 latency=7.436997916s
```
It's parsable by Grafana Loki and thus it's possible to set up alerts based on logs.  Also, retires the dependency on GCP logs gathering in favor of Grafana Loki.
> Switch to both a human- and machine- readable logging format

- http-api/src/project.rs
- http-api/src/v1.rs
- http-api/src/v1/delegates.rs
- http-api/src/v1/projects.rs
- http-api/src/v1/stats.rs
This PR adds pagination to the project root handler.
- Creates chunks of size defined by query param `per_page` and defaults to 10 projects per page.
- Gets chunk at index defined by query param `page` and defaults to first page if None given.
We had some use cases where we queried for all projects of a seed, but currently we removed all this use cases.
If this still would be necessary, I would look for a way.
Also adds a project total count property to a new `/stats` route.
> http-api: Add project list pagination

- http-api/src/v1/projects.rs
We allow setting the theme via the request, instead of configuring it via the CLI.
This allows us to implement theme switching in the UI, see: https://github.com/radicle-dev/radicle-interface/pull/298#issuecomment-1225715225.
The request would look like this:
http://127.0.0.1:8777/v1/projects/rad:git:hnrk8ueib11sen1g9n1xbt71qdns9n4gipw1o/blob/8604dc616b8531c672f4e1358a00770957bfbe94/svelte.config.js?highlight=true&theme=base16-ocean.light
If the `theme` query param isn't passed in, we fall back to the default `base16-ocean.dark` theme.
> http-api: allow specifying color theme in http request

- http-api/Cargo.toml
- http-api/src/v1/projects.rs
Allow caching activity responses for an hour.
This might improve loading times for subsequent visits of a seed index page, e.g. https://app.radicle.xyz/seeds/maple.radicle.garden.
> http-api: Set cache header for activity endpoint

- .env.maple
- .env.pine
- .env.willow
- .github/workflows/deployables.yml
- Caddyfile
- docker-compose.seed.yml
- docker-compose.yml
- linkd/Dockerfile
> Add linkd service

- git-server/src/error.rs
Requests like `GET /favicon.ico/` currently result in 5xx error tripping alerts spuriously.  This PR makes it so that 404 is returned instead.
> Return 404 on bad paths

- http-api/src/lib.rs
We should inform browsers to cache CORS preflight requests for at least 24h. This safes us in the best case multiple roundtrips between the app and the http-api.
Closes #197
> http-api: Add `max-age` attribute to CORS headers
